export const quizQuestions = [
    {
      question: "1. Which of the following is a basic hook in react?",
      options: ["useReducer", "useMemo", "useCallback", "useContext"],
      correctAnswer: 3,
      points: 10,
    },
    {
        question: "2. React is a ___",
        options: ["Frontend Framework", "Backend Framework", "JavaScript Library", "JavaScript Module"],
        correctAnswer: 2,
        points: 10,
      },
      {
        question: "3. JSX allows us to write____",
        options: ["useReducer", "useMemo", "useCallback", "useContext"],
        correctAnswer: 3,
        points: 10,
      },
      {
        question: "4. Which of the following statement must be written in a class component heading",
        options: ["extends React.Component", "extends React", "extends ReactDOM", "extends ReactRouer"],
        correctAnswer: 0,
        points: 10,
      },
      {
        question: "5. Which of the following is the current definition of components?",
        options: ["Components are the HTML elements.", "Components are the set of variables defined in ReactJS.", "Components are independent and reusable code that return HTML elements", "None of the above"],
        correctAnswer: 2,
        points: 10,
      },
      {
        question: "6. How many types of components are there in react?",
        options: ["1", "2", "3", "4"],
        correctAnswer: 1,
        points: 10,
      },
      {
        question: "7. Which of the following is the correct definition of state?",
        options: ["It is a temporary storage of elements", "It is the internal storage of components", "It is used to know about the current state of the element", "It is the permanent storage of elements"],
        correctAnswer: 1,
        points: 10,
      },
      {
        question: "8. What is the correct syntax for  arrow function?",
        options: ["()", "=>", "()=>", ">=()"],
        correctAnswer: 2,
        points: 10,
      },
      {
        question: "9. What is the correct definition of prop drilling?",
        options: ["Concept of passing data as props through intermediate components until data is reached where it is required.",
             "Concept of passing data between sibling components", "Concept of passing data to required destination as states until data is reached where it is required",
             "Concept of passing data inside the component itself"],
        correctAnswer: 0,
        points: 10,
      },
      {
        question: "10. Which technique is used in React Memo?",
        options: ["Hashing", "Memoization", "Sorting", "Pipelining"],
        correctAnswer: 1,
        points: 10,
      },
      {
        question: "11. Which of the following is wrong about redux?",
        options: ["Using redux data is easily passed between components", "Debugging and testing become easier with redux",
                    "Redux offers state persistence", "Redux can only be used with React"],
        correctAnswer: 2,
        points: 10,
      },
      {
        question: "12. What is the use of mapStateToProps() in redux?",
        options: ["The method is used to render the stored data to the component.", "The method is used to render the action creators with props to the component.",
                    "The method is used to connect redux to react prop", "The method is used to render data fetched from APIs"],
        correctAnswer: 0,
        points: 10,
      },
      {
        question: "13. Which of the following is not a method of redux store?",
        options: ["getState()", "subscribe()", "dispact()", "render()"],
        correctAnswer: 3,
        points: 10,
      },
      {
        question: "14. Which of the following is a feature of ContextAPI?",
        options: ["ContextAPI cannot be directly used in the application", "ContextAPI directly sends information from parent to child at any level",
                 "ContextAPI stops sending data to child elements", "ContextAPI encrypts data before sending"],
        correctAnswer: 1,
        points: 10,
      },
      {
        question: "15. What is a reducer in react-redux?",
        options: ["Reducers are the fundamental method of updating the redux store", "Reducers are the only source of information for the store", "Reducers are plain JavaScript objects that have the type field",
                 "Reducer takes the previous state and return a new state"],
        correctAnswer: 3,
        points: 10,
      },
 
  ];